name: flutter_tricky_layout
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/flower-1.jpeg
   - assets/images/flower-2.jpeg
   - assets/images/flower-3.jpeg
   - assets/images/flower-4.jpeg
   - assets/images/flower-5.jpeg
   - assets/images/flower-6.jpeg
   - assets/images/flower-7.jpeg